import { Order } from "./interface";

export const dummyOrders: Order[] = [
  {
    id: 1,
    customerName: "David Moore",
    customerPhone: "+1 9876543210",
    orderTime: "11:00 AM, 08 Feb, 2024",
    tableNumber: 1,
    status: "New Order",
    items: [
      { name: "Spaghetti Bolognese", price: 12.0 },
      { name: "Garlic Bread", price: 3.5 },
      { name: "Caesar Salad", price: 3.5 },
    ],
    totalAmount: 22.5,
  },
  {
    id: 2,
    customerName: "Esther Howard",
    customerPhone: "+1 9876543210",
    orderTime: "11:30 AM, 08 Feb, 2024",
    tableNumber: 2,
    status: "New Order",
    items: [
      { name: "Grilled Chicken Sandwiches", price: 14.0 },
      { name: "Greek Salad", price: 8.0 },
    ],
    totalAmount: 22.0,
  },
  {
    id: 3,
    customerName: "Jacob Jones",
    customerPhone: "+1 9876543210",
    orderTime: "12:00 PM, 08 Feb, 2024",
    tableNumber: 3,
    status: "New Order",
    items: [
      { name: "Beef Burger", price: 10.0 },
      { name: "Large French Fries", price: 8.0 },
      { name: "Chocolate Milkshake", price: 8.0 },
    ],
    totalAmount: 26.0,
  },
  {
    id: 4,
    customerName: "Arlene McCoy",
    customerPhone: "+1 9876543210",
    orderTime: "01:00 PM, 08 Feb, 2024",
    tableNumber: 5,
    status: "On Cook",
    items: [
      { name: "Chicken Alfredo Pasta", price: 13.0 },
      { name: "Garlic Bread", price: 3.5 },
      { name: "Side of Vegetables", price: 4.5 },
    ],
    totalAmount: 21.0,
  },
  {
    id: 5,
    customerName: "Eleanor Pena",
    customerPhone: "+1 9876543210",
    orderTime: "02:00 PM, 08 Feb, 2024",
    tableNumber: 6,
    status: "On Cook",
    items: [
      { name: "Veggie Burger", price: 9.0 },
      { name: "Sweet Potato Fries", price: 4.5 },
      { name: "Iced Tea", price: 2.5 },
    ],
    totalAmount: 16.0,
  },
  {
    id: 6,
    customerName: "Brooklyn Simmons",
    customerPhone: "+1 9876543210",
    orderTime: "03:00 PM, 08 Feb, 2024",
    tableNumber: 7,
    status: "On Cook",
    items: [
      { name: "BBQ Chicken Pizza", price: 12.5 },
      { name: "Caesar Salad", price: 7.0 },
      { name: "Lemonade", price: 3.0 },
    ],
    totalAmount: 22.5,
  },
  {
    id: 7,
    customerName: "Courtney Henry",
    customerPhone: "+1 9876543210",
    orderTime: "05:00 PM, 08 Feb, 2024",
    tableNumber: 9,
    status: "Cancelled",
    items: [
      { name: "Margarita Pizza", price: 10.0 },
      { name: "French Fries", price: 4.0 },
      { name: "Coke", price: 1.5 },
    ],
    totalAmount: 15.5,
  },
  {
    id: 8,
    customerName: "Devon Lane",
    customerPhone: "+1 9876543210",
    orderTime: "06:00 PM, 08 Feb, 2024",
    tableNumber: 10,
    status: "Completed",
    items: [
      { name: "Salmon Sushi", price: 15.0 },
      { name: "Miso Soup", price: 3.0 },
      { name: "Green Tea", price: 2.0 },
    ],
    totalAmount: 20.0,
  },
  {
    id: 9,
    customerName: "Ronald Richards",
    customerPhone: "+1 9876543210",
    orderTime: "07:00 PM, 08 Feb, 2024",
    tableNumber: 11,
    status: "Completed",
    items: [
      { name: "BBQ Ribs", price: 18.0 },
      { name: "Coleslaw", price: 2.5 },
      { name: "Baked Beans", price: 2.0 },
    ],
    totalAmount: 22.5,
  },
  {
    id: 10,
    customerName: "Leslie Alexander",
    customerPhone: "+1 9876543210",
    orderTime: "08:00 PM, 08 Feb, 2024",
    tableNumber: 12,
    status: "Completed",
    items: [
      { name: "Veggie Pizza", price: 12.0 },
      { name: "Garlic Knots", price: 4.0 },
      { name: "Sprite", price: 1.5 },
    ],
    totalAmount: 17.5,
  },
];
